Repository acm-ucr/hlg-website, pull requests merged in 2023-10, with the labels that each got.

#26 Add 404 Page
  src/app/not-found.js
Labels: Ready for Review, Navigation

#21 Create Event Components
  package-lock.json
  package.json
  src/app/page.js
  src/components/events/Event.jsx
Labels: Ready for Review

#23 John add heading component
  .gitignore
  src/app/about/page.js
  src/components/Heading.jsx
Labels: Ready for Review

#20 Created Slide Component
  package-lock.json
  src/components/events/Slides.jsx
Labels: Do Not Merge, Events

#39 JOIN US Button Component
  .github/workflows/nextjs.yml
  .gitignore
  package-lock.json
  package.json
  src/app/about/page.js
  src/app/layout.js
  src/app/not-found.js
  src/app/page.js
  src/components/Heading.jsx
  src/components/about/Story.jsx
  src/components/events/Event.jsx
  src/components/events/Slides.jsx
  src/components/home/LandingTitle.jsx
  src/data/team.js
Labels: Ready for Review, Ready to Merge

#44 Create Sponsors Component
  src/components/home/Sponsors.jsx
Labels: Do Not Merge, Home

#41 create button component
  src/components/Button.jsx
Labels: Ready for Review, Home

#19 Created Graves Team Component
  src/components/team/Teammate.jsx
Labels: Ready for Review, Teams

#43 Make Social component - Discord
  src/components/Social.jsx
Labels: Ready for Review, Home

#24 add navbar logo
  package-lock.json
  src/app/page.js
  src/components/Icon.jsx
Labels: Ready for Review
