Repository acm-ucr/hlg-website, pull requests merged in 2023-11, with the labels that each got.

#42 JohnZ Intro Page
  src/app/about/page.js
  src/components/home/Intro.jsx
Labels: Ready to Merge

#50 Create navigation component
  src/components/Navigation.jsx
  src/data/navigation.js
Labels: Ready for Review, Navigation

#47 Create Who Component
  src/components/about/Who.jsx
Labels: Ready for Review

#49 Map through Social Icons
  src/app/page.js
  src/components/Social.jsx
  src/data/links.js
Labels: Ready for Review, Home

#48 Component Calendar
  package-lock.json
  package.json
  src/app/events/page.js
  src/components/events/Calendar.jsx
  src/components/events/CustomEvent.jsx
  src/components/events/CustomHeader.jsx
  src/components/events/CustomToolbar.jsx
  src/components/events/Modal.jsx
  src/data/events.js
  src/data/filters.js
Labels: Ready for Review

#63 Create events component
  src/components/events/Event.jsx
  src/components/events/Events.jsx
  src/data/events.js
Labels: Ready for Review, Events

#64 JohnZ/staff component
  src/app/staff/page.js
  src/components/staff/Staff.jsx
Labels: Ready to Merge

#46 Map through team objects
  src/app/team/page.js
  src/components/team/Teammate.jsx
  src/components/team/Teammates.jsx
  src/data/team.js
Labels: Ready for Review, Teams

#70 JohnZ/staffpage
  src/app/staff/page.js
Labels: Staff

#68 Make Landing Title Component
  src/components/Button.jsx
  src/components/home/Landing.jsx
  src/components/home/LandingTitle.jsx
Labels: Do Not Merge, Home

#76 Issue #66 Change Header and add grey background
  src/app/page.js
  src/components/home/Intro.jsx
Labels: Ready for Review

#78 Fixed mobile navbar
  src/components/Navigation.jsx
Labels: Ready for Review, Navigation

#77 Add Banner
  src/app/about/page.js
  src/app/events/page.js
  src/app/staff/page.js
  src/app/team/page.js
  src/components/Banner.jsx
Labels: Ready for Review, General

#80 Fix mobile for Intro.jsx
  src/components/home/Intro.jsx
  src/components/home/Landing.jsx
Labels: Ready for Review

#74 Make Team page responsive
  src/app/staff/page.js
  src/app/team/page.js
  src/components/staff/Staff.jsx
  src/components/team/Teammates.jsx
  src/data/staff.js
Labels: Ready for Review

#95 Update socials on mobile for responsivness
  src/app/page.js
Labels: Ready for Review, Home

#94 center calendar
  src/app/events/page.js
Labels: Ready for Review, Events

#89 fixed all spacings on landing page
  src/components/home/Intro.jsx
Labels: Ready for Review

#101 footer spacing
  src/app/layout.js
  src/app/staff/page.js
  src/app/team/page.js
  src/components/home/Intro.jsx
Labels: Ready for Review

#100 fixed the grey gap error
  src/app/page.js
  src/components/home/Intro.jsx
Labels: Ready for Review
