Repository acm-ucr/hlg-website, pull requests merged in 2023-12, with the labels that each got.

#115 Ishaan/Mobile Responsiveness Our Story
  src/components/about/Story.jsx
  src/components/about/Who.jsx
Labels: About

#119 404 page format error
  src/app/layout.js
  src/app/not-found.js
  src/components/Footer.jsx
Labels: Ready for Review

#91 Added Landing component
  src/app/page.js
  src/components/Button.jsx
  src/components/Footer.jsx
  src/components/home/Landing.jsx
  src/components/home/LandingTitle.jsx
  src/data/links.js
Labels: Ready for Review

#113 Integrated real staff data
  package-lock.json
  package.json
  public/awesome-cat-placeholder.png
  src/app/staff/page.js
  src/components/staff/Staff.jsx
  src/data/staff.js
Labels: Do Not Merge
